/* My IDE was giving errors about non existent columns (when do they exist), these commands suppress those errors */
-- noinspection SqlResolveForFile
-- noinspection SqlInsertValuesForFile

/* Insert moods */
insert into moods (mood) values ('chill');
insert into moods (mood) values ('cultural');
insert into moods (mood) values ('happy');
insert into moods (mood) values ('hungry');
insert into moods (mood) values ('party');
insert into moods (mood) values ('surprise me');

/* Insert interests */
insert into interests (interest) values ('Travelling');
insert into interests (interest) values ('Food');
insert into interests (interest) values ('Partying');
insert into interests (interest) values ('Reading');
insert into interests (interest) values ('Beach');
insert into interests (interest) values ('Painting');
insert into interests (interest) values ('Blogging');
insert into interests (interest) values ('Camping');
insert into interests (interest) values ('Movies');
insert into interests (interest) values ('Photography');
insert into interests (interest) values ('Acrobatics');
insert into interests (interest) values ('Baking');
insert into interests (interest) values ('Board games');
insert into interests (interest) values ('Cosplay');
insert into interests (interest) values ('Filmmaking');
insert into interests (interest) values ('Fashion');
insert into interests (interest) values ('Sports');
insert into interests (interest) values ('Knitting');
insert into interests (interest) values ('Colouring');
insert into interests (interest) values ('Programming');
insert into interests (interest) values ('Coding');
insert into interests (interest) values ('Cooking');
insert into interests (interest) values ('Singing');
insert into interests (interest) values ('Dancing');
insert into interests (interest) values ('Video games');
insert into interests (interest) values ('DIY');
insert into interests (interest) values ('Ice skating');
insert into interests (interest) values ('Karate');
insert into interests (interest) values ('Tennis');
insert into interests (interest) values ('Hurling');
insert into interests (interest) values ('Cycling');
insert into interests (interest) values ('Walking');
insert into interests (interest) values ('History');
insert into interests (interest) values ('Biology');
insert into interests (interest) values ('Fencing');
insert into interests (interest) values ('Meditation');
insert into interests (interest) values ('Blogging');
insert into interests (interest) values ('Beekeeping');
insert into interests (interest) values ('Graphic Design');
insert into interests (interest) values ('Vlogging');
insert into interests (interest) values ('Playing music');
insert into interests (interest) values ('Candle making');
insert into interests (interest) values ('Zumba');
insert into interests (interest) values ('Sewing');
insert into interests (interest) values ('Mapping');
insert into interests (interest) values ('Netflix');
insert into interests (interest) values ('Orienteering');
insert into interests (interest) values ('Up-cycling');
insert into interests (interest) values ('Organising');
insert into interests (interest) values ('Chess');
insert into interests (interest) values ('Sudoku');
insert into interests (interest) values ('Boxing');
insert into interests (interest) values ('Archery');
insert into interests (interest) values ('Racing');
insert into interests (interest) values ('Gadgets');
insert into interests (interest) values ('Technology');
insert into interests (interest) values ('Hiking');
insert into interests (interest) values ('Architecture');
insert into interests (interest) values ('Beat boxing');
insert into interests (interest) values ('Paragliding');
insert into interests (interest) values ('Yoga');
insert into interests (interest) values ('Pilates');
insert into interests (interest) values ('Snorkeling');
insert into interests (interest) values ('Massage');
insert into interests (interest) values ('Wine tasting');
insert into interests (interest) values ('Ballroom dancing');
insert into interests (interest) values ('Star gazing');
insert into interests (interest) values ('Picnicking');

/* Insert venues
* Self created ID for easier associating with venue images, mood-venue links, venue-interest links */
insert into venues (id, venue, gpslon, gpslat, url) values (1, 'Iveagh Gardens', 53.3353491, -6.2604937, 'http://iveaghgardens.ie/');
insert into venues (id, venue, gpslon, gpslat, url) values (2, 'Phoenix Park', 53.3585521, -6.3242769, 'http://phoenixpark.ie/');
insert into venues (id, venue, gpslon, gpslat, url) values (3, 'Tea Garden', 53.346208, -6.266986, 'https://www.teagarden.ie/');
insert into venues (id, venue, gpslon, gpslat, url) values (4, 'Botanic Gardens', 53.372316, -6.268738, 'http://botanicgardens.ie/');
insert into venues (id, venue, gpslon, gpslat, url) values (5, 'Dollymount Strand', 53.3659789, -6.1742388, null);
insert into venues (id, venue, gpslon, gpslat, url) values (6, 'Olesya''s Wine Bar', 53.342951, -6.263236, 'http://www.olesyaswinebar.com/');
insert into venues (id, venue, gpslon, gpslat, url) values (7, 'Accents Coffee & Tea Lounge', 53.3412721,  -6.2648794, 'https://accentslounge.wordpress.com/');
insert into venues (id, venue, gpslon, gpslat, url) values (8, 'Poolbeg Lighthouse', 53.3421076, -6.151368393647876, null);
insert into venues (id, venue, gpslon, gpslat, url) values (9, 'Merrion Square Park', 53.339676350000005, -6.249173779740449, null);

insert into venues (id, venue, gpslon, gpslat, url) values (10, 'Graphic Studio Gallery', 53.344994, -6.262273, 'https://graphicstudiodublin.com/');
insert into venues (id, venue, gpslon, gpslat, url) values (11, 'Natural History Museum', 53.339885, -6.253348, 'https://www.museum.ie/en-IE/Museums/Natural-History');
insert into venues (id, venue, gpslon, gpslat, url) values (12, 'National Photographic Archive', 53.345184, -6.265382, 'https://www.nli.ie/en/national-photographic-archive.aspx');
insert into venues (id, venue, gpslon, gpslat, url) values (13, 'Irish Musuem of Modern Art', 53.342917, -6.300048, 'https://imma.ie/');
insert into venues (id, venue, gpslon, gpslat, url) values (14, 'General Post Office', 53.349349, -6.260721, 'https://www.gpowitnesshistory.ie/');
insert into venues (id, venue, gpslon, gpslat, url) values (15, 'Christ Church Cathedral', 53.343513, -6.27106, 'https://christchurchcathedral.ie/');
insert into venues (id, venue, gpslon, gpslat, url) values (16, 'EPIC Irish Emigration Museum', 53.3482653, -6.2479785, 'https://epicchq.com/');
insert into venues (id, venue, gpslon, gpslat, url) values (17, 'Kilmainham Gaol', 53.34174585, -6.309578660652412, 'http://kilmainhamgaolmuseum.ie/');
insert into venues (id, venue, gpslon, gpslat, url) values (43, 'Trinity College Dublin', 53.34366745, -6.254444724511822, null);
insert into venues (id, venue, gpslon, gpslat, url) values (44, 'Dublin Castle', 53.343175099999996, -6.268434702874895, 'https://www.dublincastle.ie/');

insert into venues (id, venue, gpslon, gpslat, url) values (18, 'Skyline Tour Croke Park', 53.360712, -6.251209, 'https://crokepark.ie/skyline');
insert into venues (id, venue, gpslon, gpslat, url) values (19, 'St. Stephen''s Green', 53.338174, -6.259119, 'http://ststephensgreenpark.ie/');
insert into venues (id, venue, gpslon, gpslat, url) values (20, 'The Chocolate Warehouse', 53.315336, -6.33297, null);
insert into venues (id, venue, gpslon, gpslat, url) values (21, 'Vertigo Outdoor', 53.0107896, -6.108289, 'http://vertigo-outdoor.com/');
insert into venues (id, venue, gpslon, gpslat, url) values (22, 'Jumpzone', 53.280432, -6.216982, 'https://jumpzone.ie/');
insert into venues (id, venue, gpslon, gpslat, url) values (23, 'Kylemore Karting', 53.343513, -6.27106, 'https://www.kylemorekarting.ie/');
insert into venues (id, venue, gpslon, gpslat, url) values (24, 'Wakedock', 53.343514049999996, -6.234646711633417, 'https://www.wakedock.ie/');
insert into venues (id, venue, gpslon, gpslat, url) values (25, 'Rainforest Adventure Golf', 53.2858306, -6.2392629, 'https://www.rainforestadventuregolf.ie/');
insert into venues (id, venue, gpslon, gpslat, url) values (26, 'Science Gallery', 53.3441672, -6.2505382, 'https://dublin.sciencegallery.com/');

insert into venues (id, venue, gpslon, gpslat, url) values (27, 'Sabor Brasil', 53.334942, -6.265508, null);
insert into venues (id, venue, gpslon, gpslat, url) values (28, 'Veda', 53.2648502, -6.1517449, 'https://www.vedarestaurant.ie/');
insert into venues (id, venue, gpslon, gpslat, url) values (29, 'The Vintage Kitchen', 53.346208, -6.266986, 'https://thevintagekitchen.ie/');
insert into venues (id, venue, gpslon, gpslat, url) values (30, 'F.X. Buckley Steakhouse', 53.346907, -6.255695, 'https://www.fxbuckley.ie/');
insert into venues (id, venue, gpslon, gpslat, url) values (31, 'I Monelli', 53.3101681, -6.2714624, 'https://imonelli.ie/');
insert into venues (id, venue, gpslon, gpslat, url) values (32, 'Restaurant Patrick Guilbaud', 53.338352, -6.252895, 'https://restaurantpatrickguilbaud.ie/');
insert into venues (id, venue, gpslon, gpslat, url) values (33, 'Dollard & Co.', 53.3452889, -6.2672109, 'https://dollardandco.ie/');
insert into venues (id, venue, gpslon, gpslat, url) values (34, 'East Road', 53.3563465, -6.2315507, null);
insert into venues (id, venue, gpslon, gpslat, url) values (35, 'Dublin Pizza Company', 53.3390019, -6.2658266, 'https://www.dublinpizzacompany.ie/');

insert into venues (id, venue, gpslon, gpslat, url) values (36, 'Dtwo', 53.33442540000001, -6.262742900000035, 'https://www.dtwonightclub.com/');
insert into venues (id, venue, gpslon, gpslat, url) values (37, 'Diceys', 53.3325457, -6.263797000000068, 'http://www.russellcourthotel.ie/diceys-garden/');
insert into venues (id, venue, gpslon, gpslat, url) values (38, 'Coppers', 53.3353775, -6.263598900000034, 'http://copperfacejacks.ie/');
insert into venues (id, venue, gpslon, gpslat, url) values (39, 'Dandelions', 53.33918569999999, -6.2613254000000325, 'https://www.facebook.com/dandelionclub/');
insert into venues (id, venue, gpslon, gpslat, url) values (40, 'Twisted Pepper', 53.3478286, -6.262294900000029, null);
insert into venues (id, venue, gpslon, gpslat, url) values (41, 'The Workman''s Clubs', 53.3453862, -6.2664774, 'https://theworkmansclub.com/');
insert into venues (id, venue, gpslon, gpslat, url) values (42, 'The George', 53.3437938, -6.2646675, 'http://thegeorge.ie/');
insert into venues (id, venue, gpslon, gpslat, url) values (45, 'Everleigh Garden', 53.3351615, -6.2634856, 'https://everleigh.ie/');
insert into venues (id, venue, gpslon, gpslat, url) values (46, 'Opium', 53.3367018, -6.2656562, 'http://opium.ie/');

/* Insert links between mood and venue
* Table necessary for many-to-many relationship between moods and venues tables */
insert into moodvenuelink (moodid, venueid) values (1, 1);
insert into moodvenuelink (moodid, venueid) values (1, 2);
insert into moodvenuelink (moodid, venueid) values (1, 3);
insert into moodvenuelink (moodid, venueid) values (1, 4);
insert into moodvenuelink (moodid, venueid) values (1, 5);
insert into moodvenuelink (moodid, venueid) values (1, 6);
insert into moodvenuelink (moodid, venueid) values (1, 7);
insert into moodvenuelink (moodid, venueid) values (1, 8);
insert into moodvenuelink (moodid, venueid) values (1, 9);
insert into moodvenuelink (moodid, venueid) values (2, 10);
insert into moodvenuelink (moodid, venueid) values (2, 11);
insert into moodvenuelink (moodid, venueid) values (2, 12);
insert into moodvenuelink (moodid, venueid) values (2, 13);
insert into moodvenuelink (moodid, venueid) values (2, 14);
insert into moodvenuelink (moodid, venueid) values (2, 15);
insert into moodvenuelink (moodid, venueid) values (2, 16);
insert into moodvenuelink (moodid, venueid) values (2, 17);
insert into moodvenuelink (moodid, venueid) values (2, 43);
insert into moodvenuelink (moodid, venueid) values (2, 44);
insert into moodvenuelink (moodid, venueid) values (3, 18);
insert into moodvenuelink (moodid, venueid) values (3, 19);
insert into moodvenuelink (moodid, venueid) values (3, 20);
insert into moodvenuelink (moodid, venueid) values (3, 21);
insert into moodvenuelink (moodid, venueid) values (3, 22);
insert into moodvenuelink (moodid, venueid) values (3, 23);
insert into moodvenuelink (moodid, venueid) values (3, 24);
insert into moodvenuelink (moodid, venueid) values (3, 25);
insert into moodvenuelink (moodid, venueid) values (3, 26);
insert into moodvenuelink (moodid, venueid) values (4, 27);
insert into moodvenuelink (moodid, venueid) values (4, 28);
insert into moodvenuelink (moodid, venueid) values (4, 29);
insert into moodvenuelink (moodid, venueid) values (4, 30);
insert into moodvenuelink (moodid, venueid) values (4, 31);
insert into moodvenuelink (moodid, venueid) values (4, 32);
insert into moodvenuelink (moodid, venueid) values (4, 33);
insert into moodvenuelink (moodid, venueid) values (4, 34);
insert into moodvenuelink (moodid, venueid) values (4, 35);
insert into moodvenuelink (moodid, venueid) values (5, 36);
insert into moodvenuelink (moodid, venueid) values (5, 37);
insert into moodvenuelink (moodid, venueid) values (5, 38);
insert into moodvenuelink (moodid, venueid) values (5, 39);
insert into moodvenuelink (moodid, venueid) values (5, 40);
insert into moodvenuelink (moodid, venueid) values (5, 41);
insert into moodvenuelink (moodid, venueid) values (5, 42);
insert into moodvenuelink (moodid, venueid) values (5, 45);
insert into moodvenuelink (moodid, venueid) values (5, 46);

/* Insert links between venues and moods
* Table necessary for many-to-many relationship between venues and interests tables
* The interests linked to the venues are random and were auto generated for this purpose to save time
* Therefore, the venue interest scores displayed on the site will not be accurate for the venues
* but will be an accurate representation of the link between user interests and the random interests assigned to that venue*/
insert into venueinterestlink (venueid, interestid) values (1, 18);
insert into venueinterestlink (venueid, interestid) values (1, 47);
insert into venueinterestlink (venueid, interestid) values (1, 36);
insert into venueinterestlink (venueid, interestid) values (1, 12);
insert into venueinterestlink (venueid, interestid) values (1, 20);
insert into venueinterestlink (venueid, interestid) values (1, 21);
insert into venueinterestlink (venueid, interestid) values (1, 42);
insert into venueinterestlink (venueid, interestid) values (1, 61);
insert into venueinterestlink (venueid, interestid) values (1, 31);
insert into venueinterestlink (venueid, interestid) values (1, 65);
insert into venueinterestlink (venueid, interestid) values (1, 9);
insert into venueinterestlink (venueid, interestid) values (1, 7);
insert into venueinterestlink (venueid, interestid) values (1, 44);
insert into venueinterestlink (venueid, interestid) values (1, 54);
insert into venueinterestlink (venueid, interestid) values (1, 4);
insert into venueinterestlink (venueid, interestid) values (1, 49);
insert into venueinterestlink (venueid, interestid) values (1, 28);
insert into venueinterestlink (venueid, interestid) values (1, 41);
insert into venueinterestlink (venueid, interestid) values (1, 51);
insert into venueinterestlink (venueid, interestid) values (1, 60);
insert into venueinterestlink (venueid, interestid) values (2, 51);
insert into venueinterestlink (venueid, interestid) values (2, 3);
insert into venueinterestlink (venueid, interestid) values (2, 21);
insert into venueinterestlink (venueid, interestid) values (2, 17);
insert into venueinterestlink (venueid, interestid) values (2, 15);
insert into venueinterestlink (venueid, interestid) values (2, 60);
insert into venueinterestlink (venueid, interestid) values (2, 43);
insert into venueinterestlink (venueid, interestid) values (2, 2);
insert into venueinterestlink (venueid, interestid) values (2, 20);
insert into venueinterestlink (venueid, interestid) values (2, 32);
insert into venueinterestlink (venueid, interestid) values (2, 31);
insert into venueinterestlink (venueid, interestid) values (2, 49);
insert into venueinterestlink (venueid, interestid) values (2, 16);
insert into venueinterestlink (venueid, interestid) values (2, 64);
insert into venueinterestlink (venueid, interestid) values (2, 25);
insert into venueinterestlink (venueid, interestid) values (2, 5);
insert into venueinterestlink (venueid, interestid) values (2, 59);
insert into venueinterestlink (venueid, interestid) values (2, 36);
insert into venueinterestlink (venueid, interestid) values (2, 50);
insert into venueinterestlink (venueid, interestid) values (2, 35);
insert into venueinterestlink (venueid, interestid) values (3, 15);
insert into venueinterestlink (venueid, interestid) values (3, 64);
insert into venueinterestlink (venueid, interestid) values (3, 63);
insert into venueinterestlink (venueid, interestid) values (3, 13);
insert into venueinterestlink (venueid, interestid) values (3, 54);
insert into venueinterestlink (venueid, interestid) values (3, 11);
insert into venueinterestlink (venueid, interestid) values (3, 33);
insert into venueinterestlink (venueid, interestid) values (3, 45);
insert into venueinterestlink (venueid, interestid) values (3, 49);
insert into venueinterestlink (venueid, interestid) values (3, 43);
insert into venueinterestlink (venueid, interestid) values (3, 59);
insert into venueinterestlink (venueid, interestid) values (3, 65);
insert into venueinterestlink (venueid, interestid) values (3, 42);
insert into venueinterestlink (venueid, interestid) values (3, 32);
insert into venueinterestlink (venueid, interestid) values (3, 51);
insert into venueinterestlink (venueid, interestid) values (3, 60);
insert into venueinterestlink (venueid, interestid) values (3, 9);
insert into venueinterestlink (venueid, interestid) values (3, 41);
insert into venueinterestlink (venueid, interestid) values (3, 27);
insert into venueinterestlink (venueid, interestid) values (3, 18);
insert into venueinterestlink (venueid, interestid) values (4, 53);
insert into venueinterestlink (venueid, interestid) values (4, 10);
insert into venueinterestlink (venueid, interestid) values (4, 64);
insert into venueinterestlink (venueid, interestid) values (4, 33);
insert into venueinterestlink (venueid, interestid) values (4, 63);
insert into venueinterestlink (venueid, interestid) values (4, 4);
insert into venueinterestlink (venueid, interestid) values (4, 37);
insert into venueinterestlink (venueid, interestid) values (4, 3);
insert into venueinterestlink (venueid, interestid) values (4, 9);
insert into venueinterestlink (venueid, interestid) values (4, 42);
insert into venueinterestlink (venueid, interestid) values (4, 58);
insert into venueinterestlink (venueid, interestid) values (4, 29);
insert into venueinterestlink (venueid, interestid) values (4, 1);
insert into venueinterestlink (venueid, interestid) values (4, 52);
insert into venueinterestlink (venueid, interestid) values (4, 50);
insert into venueinterestlink (venueid, interestid) values (4, 41);
insert into venueinterestlink (venueid, interestid) values (4, 13);
insert into venueinterestlink (venueid, interestid) values (4, 18);
insert into venueinterestlink (venueid, interestid) values (4, 30);
insert into venueinterestlink (venueid, interestid) values (4, 46);
insert into venueinterestlink (venueid, interestid) values (5, 55);
insert into venueinterestlink (venueid, interestid) values (5, 42);
insert into venueinterestlink (venueid, interestid) values (5, 57);
insert into venueinterestlink (venueid, interestid) values (5, 59);
insert into venueinterestlink (venueid, interestid) values (5, 60);
insert into venueinterestlink (venueid, interestid) values (5, 50);
insert into venueinterestlink (venueid, interestid) values (5, 4);
insert into venueinterestlink (venueid, interestid) values (5, 28);
insert into venueinterestlink (venueid, interestid) values (5, 10);
insert into venueinterestlink (venueid, interestid) values (5, 18);
insert into venueinterestlink (venueid, interestid) values (5, 12);
insert into venueinterestlink (venueid, interestid) values (5, 39);
insert into venueinterestlink (venueid, interestid) values (5, 0);
insert into venueinterestlink (venueid, interestid) values (5, 31);
insert into venueinterestlink (venueid, interestid) values (5, 54);
insert into venueinterestlink (venueid, interestid) values (5, 51);
insert into venueinterestlink (venueid, interestid) values (5, 15);
insert into venueinterestlink (venueid, interestid) values (5, 56);
insert into venueinterestlink (venueid, interestid) values (5, 33);
insert into venueinterestlink (venueid, interestid) values (5, 3);
insert into venueinterestlink (venueid, interestid) values (6, 44);
insert into venueinterestlink (venueid, interestid) values (6, 62);
insert into venueinterestlink (venueid, interestid) values (6, 10);
insert into venueinterestlink (venueid, interestid) values (6, 43);
insert into venueinterestlink (venueid, interestid) values (6, 45);
insert into venueinterestlink (venueid, interestid) values (6, 6);
insert into venueinterestlink (venueid, interestid) values (6, 42);
insert into venueinterestlink (venueid, interestid) values (6, 55);
insert into venueinterestlink (venueid, interestid) values (6, 53);
insert into venueinterestlink (venueid, interestid) values (6, 29);
insert into venueinterestlink (venueid, interestid) values (6, 19);
insert into venueinterestlink (venueid, interestid) values (6, 64);
insert into venueinterestlink (venueid, interestid) values (6, 25);
insert into venueinterestlink (venueid, interestid) values (6, 1);
insert into venueinterestlink (venueid, interestid) values (6, 39);
insert into venueinterestlink (venueid, interestid) values (6, 31);
insert into venueinterestlink (venueid, interestid) values (6, 20);
insert into venueinterestlink (venueid, interestid) values (6, 60);
insert into venueinterestlink (venueid, interestid) values (6, 11);
insert into venueinterestlink (venueid, interestid) values (6, 21);
insert into venueinterestlink (venueid, interestid) values (7, 15);
insert into venueinterestlink (venueid, interestid) values (7, 9);
insert into venueinterestlink (venueid, interestid) values (7, 30);
insert into venueinterestlink (venueid, interestid) values (7, 40);
insert into venueinterestlink (venueid, interestid) values (7, 48);
insert into venueinterestlink (venueid, interestid) values (7, 23);
insert into venueinterestlink (venueid, interestid) values (7, 59);
insert into venueinterestlink (venueid, interestid) values (7, 60);
insert into venueinterestlink (venueid, interestid) values (7, 42);
insert into venueinterestlink (venueid, interestid) values (7, 41);
insert into venueinterestlink (venueid, interestid) values (7, 52);
insert into venueinterestlink (venueid, interestid) values (7, 8);
insert into venueinterestlink (venueid, interestid) values (7, 25);
insert into venueinterestlink (venueid, interestid) values (7, 0);
insert into venueinterestlink (venueid, interestid) values (7, 4);
insert into venueinterestlink (venueid, interestid) values (7, 21);
insert into venueinterestlink (venueid, interestid) values (7, 65);
insert into venueinterestlink (venueid, interestid) values (7, 35);
insert into venueinterestlink (venueid, interestid) values (7, 10);
insert into venueinterestlink (venueid, interestid) values (7, 3);
insert into venueinterestlink (venueid, interestid) values (8, 7);
insert into venueinterestlink (venueid, interestid) values (8, 44);
insert into venueinterestlink (venueid, interestid) values (8, 49);
insert into venueinterestlink (venueid, interestid) values (8, 55);
insert into venueinterestlink (venueid, interestid) values (8, 20);
insert into venueinterestlink (venueid, interestid) values (8, 19);
insert into venueinterestlink (venueid, interestid) values (8, 13);
insert into venueinterestlink (venueid, interestid) values (8, 8);
insert into venueinterestlink (venueid, interestid) values (8, 41);
insert into venueinterestlink (venueid, interestid) values (8, 58);
insert into venueinterestlink (venueid, interestid) values (8, 39);
insert into venueinterestlink (venueid, interestid) values (8, 1);
insert into venueinterestlink (venueid, interestid) values (8, 52);
insert into venueinterestlink (venueid, interestid) values (8, 31);
insert into venueinterestlink (venueid, interestid) values (8, 15);
insert into venueinterestlink (venueid, interestid) values (8, 18);
insert into venueinterestlink (venueid, interestid) values (8, 22);
insert into venueinterestlink (venueid, interestid) values (8, 50);
insert into venueinterestlink (venueid, interestid) values (8, 12);
insert into venueinterestlink (venueid, interestid) values (8, 57);
insert into venueinterestlink (venueid, interestid) values (9, 24);
insert into venueinterestlink (venueid, interestid) values (9, 41);
insert into venueinterestlink (venueid, interestid) values (9, 32);
insert into venueinterestlink (venueid, interestid) values (9, 60);
insert into venueinterestlink (venueid, interestid) values (9, 5);
insert into venueinterestlink (venueid, interestid) values (9, 22);
insert into venueinterestlink (venueid, interestid) values (9, 31);
insert into venueinterestlink (venueid, interestid) values (9, 45);
insert into venueinterestlink (venueid, interestid) values (9, 11);
insert into venueinterestlink (venueid, interestid) values (9, 61);
insert into venueinterestlink (venueid, interestid) values (9, 43);
insert into venueinterestlink (venueid, interestid) values (9, 64);
insert into venueinterestlink (venueid, interestid) values (9, 38);
insert into venueinterestlink (venueid, interestid) values (9, 21);
insert into venueinterestlink (venueid, interestid) values (9, 48);
insert into venueinterestlink (venueid, interestid) values (9, 59);
insert into venueinterestlink (venueid, interestid) values (9, 8);
insert into venueinterestlink (venueid, interestid) values (9, 58);
insert into venueinterestlink (venueid, interestid) values (9, 54);
insert into venueinterestlink (venueid, interestid) values (9, 3);
insert into venueinterestlink (venueid, interestid) values (10, 58);
insert into venueinterestlink (venueid, interestid) values (10, 20);
insert into venueinterestlink (venueid, interestid) values (10, 51);
insert into venueinterestlink (venueid, interestid) values (10, 32);
insert into venueinterestlink (venueid, interestid) values (10, 57);
insert into venueinterestlink (venueid, interestid) values (10, 61);
insert into venueinterestlink (venueid, interestid) values (10, 55);
insert into venueinterestlink (venueid, interestid) values (10, 4);
insert into venueinterestlink (venueid, interestid) values (10, 28);
insert into venueinterestlink (venueid, interestid) values (10, 24);
insert into venueinterestlink (venueid, interestid) values (10, 60);
insert into venueinterestlink (venueid, interestid) values (10, 31);
insert into venueinterestlink (venueid, interestid) values (10, 65);
insert into venueinterestlink (venueid, interestid) values (10, 49);
insert into venueinterestlink (venueid, interestid) values (10, 5);
insert into venueinterestlink (venueid, interestid) values (10, 34);
insert into venueinterestlink (venueid, interestid) values (10, 30);
insert into venueinterestlink (venueid, interestid) values (10, 63);
insert into venueinterestlink (venueid, interestid) values (10, 36);
insert into venueinterestlink (venueid, interestid) values (10, 21);
insert into venueinterestlink (venueid, interestid) values (11, 35);
insert into venueinterestlink (venueid, interestid) values (11, 40);
insert into venueinterestlink (venueid, interestid) values (11, 12);
insert into venueinterestlink (venueid, interestid) values (11, 56);
insert into venueinterestlink (venueid, interestid) values (11, 4);
insert into venueinterestlink (venueid, interestid) values (11, 57);
insert into venueinterestlink (venueid, interestid) values (11, 18);
insert into venueinterestlink (venueid, interestid) values (11, 0);
insert into venueinterestlink (venueid, interestid) values (11, 15);
insert into venueinterestlink (venueid, interestid) values (11, 46);
insert into venueinterestlink (venueid, interestid) values (11, 49);
insert into venueinterestlink (venueid, interestid) values (11, 58);
insert into venueinterestlink (venueid, interestid) values (11, 25);
insert into venueinterestlink (venueid, interestid) values (11, 3);
insert into venueinterestlink (venueid, interestid) values (11, 53);
insert into venueinterestlink (venueid, interestid) values (11, 52);
insert into venueinterestlink (venueid, interestid) values (11, 17);
insert into venueinterestlink (venueid, interestid) values (11, 55);
insert into venueinterestlink (venueid, interestid) values (11, 59);
insert into venueinterestlink (venueid, interestid) values (11, 41);
insert into venueinterestlink (venueid, interestid) values (12, 27);
insert into venueinterestlink (venueid, interestid) values (12, 35);
insert into venueinterestlink (venueid, interestid) values (12, 52);
insert into venueinterestlink (venueid, interestid) values (12, 39);
insert into venueinterestlink (venueid, interestid) values (12, 51);
insert into venueinterestlink (venueid, interestid) values (12, 60);
insert into venueinterestlink (venueid, interestid) values (12, 2);
insert into venueinterestlink (venueid, interestid) values (12, 11);
insert into venueinterestlink (venueid, interestid) values (12, 6);
insert into venueinterestlink (venueid, interestid) values (12, 55);
insert into venueinterestlink (venueid, interestid) values (12, 34);
insert into venueinterestlink (venueid, interestid) values (12, 13);
insert into venueinterestlink (venueid, interestid) values (12, 45);
insert into venueinterestlink (venueid, interestid) values (12, 44);
insert into venueinterestlink (venueid, interestid) values (12, 30);
insert into venueinterestlink (venueid, interestid) values (12, 17);
insert into venueinterestlink (venueid, interestid) values (12, 57);
insert into venueinterestlink (venueid, interestid) values (12, 16);
insert into venueinterestlink (venueid, interestid) values (12, 33);
insert into venueinterestlink (venueid, interestid) values (12, 29);
insert into venueinterestlink (venueid, interestid) values (13, 17);
insert into venueinterestlink (venueid, interestid) values (13, 23);
insert into venueinterestlink (venueid, interestid) values (13, 42);
insert into venueinterestlink (venueid, interestid) values (13, 35);
insert into venueinterestlink (venueid, interestid) values (13, 64);
insert into venueinterestlink (venueid, interestid) values (13, 54);
insert into venueinterestlink (venueid, interestid) values (13, 49);
insert into venueinterestlink (venueid, interestid) values (13, 32);
insert into venueinterestlink (venueid, interestid) values (13, 24);
insert into venueinterestlink (venueid, interestid) values (13, 61);
insert into venueinterestlink (venueid, interestid) values (13, 60);
insert into venueinterestlink (venueid, interestid) values (13, 36);
insert into venueinterestlink (venueid, interestid) values (13, 20);
insert into venueinterestlink (venueid, interestid) values (13, 37);
insert into venueinterestlink (venueid, interestid) values (13, 48);
insert into venueinterestlink (venueid, interestid) values (13, 14);
insert into venueinterestlink (venueid, interestid) values (13, 1);
insert into venueinterestlink (venueid, interestid) values (13, 41);
insert into venueinterestlink (venueid, interestid) values (13, 30);
insert into venueinterestlink (venueid, interestid) values (13, 29);
insert into venueinterestlink (venueid, interestid) values (14, 55);
insert into venueinterestlink (venueid, interestid) values (14, 44);
insert into venueinterestlink (venueid, interestid) values (14, 41);
insert into venueinterestlink (venueid, interestid) values (14, 42);
insert into venueinterestlink (venueid, interestid) values (14, 1);
insert into venueinterestlink (venueid, interestid) values (14, 14);
insert into venueinterestlink (venueid, interestid) values (14, 61);
insert into venueinterestlink (venueid, interestid) values (14, 37);
insert into venueinterestlink (venueid, interestid) values (14, 38);
insert into venueinterestlink (venueid, interestid) values (14, 63);
insert into venueinterestlink (venueid, interestid) values (14, 30);
insert into venueinterestlink (venueid, interestid) values (14, 8);
insert into venueinterestlink (venueid, interestid) values (14, 15);
insert into venueinterestlink (venueid, interestid) values (14, 64);
insert into venueinterestlink (venueid, interestid) values (14, 33);
insert into venueinterestlink (venueid, interestid) values (14, 9);
insert into venueinterestlink (venueid, interestid) values (14, 26);
insert into venueinterestlink (venueid, interestid) values (14, 31);
insert into venueinterestlink (venueid, interestid) values (14, 50);
insert into venueinterestlink (venueid, interestid) values (14, 4);
insert into venueinterestlink (venueid, interestid) values (15, 11);
insert into venueinterestlink (venueid, interestid) values (15, 36);
insert into venueinterestlink (venueid, interestid) values (15, 13);
insert into venueinterestlink (venueid, interestid) values (15, 52);
insert into venueinterestlink (venueid, interestid) values (15, 65);
insert into venueinterestlink (venueid, interestid) values (15, 37);
insert into venueinterestlink (venueid, interestid) values (15, 55);
insert into venueinterestlink (venueid, interestid) values (15, 58);
insert into venueinterestlink (venueid, interestid) values (15, 41);
insert into venueinterestlink (venueid, interestid) values (15, 3);
insert into venueinterestlink (venueid, interestid) values (15, 46);
insert into venueinterestlink (venueid, interestid) values (15, 1);
insert into venueinterestlink (venueid, interestid) values (15, 50);
insert into venueinterestlink (venueid, interestid) values (15, 23);
insert into venueinterestlink (venueid, interestid) values (15, 19);
insert into venueinterestlink (venueid, interestid) values (15, 32);
insert into venueinterestlink (venueid, interestid) values (15, 26);
insert into venueinterestlink (venueid, interestid) values (15, 57);
insert into venueinterestlink (venueid, interestid) values (15, 22);
insert into venueinterestlink (venueid, interestid) values (15, 38);
insert into venueinterestlink (venueid, interestid) values (16, 63);
insert into venueinterestlink (venueid, interestid) values (16, 49);
insert into venueinterestlink (venueid, interestid) values (16, 50);
insert into venueinterestlink (venueid, interestid) values (16, 18);
insert into venueinterestlink (venueid, interestid) values (16, 23);
insert into venueinterestlink (venueid, interestid) values (16, 9);
insert into venueinterestlink (venueid, interestid) values (16, 35);
insert into venueinterestlink (venueid, interestid) values (16, 30);
insert into venueinterestlink (venueid, interestid) values (16, 11);
insert into venueinterestlink (venueid, interestid) values (16, 21);
insert into venueinterestlink (venueid, interestid) values (16, 46);
insert into venueinterestlink (venueid, interestid) values (16, 26);
insert into venueinterestlink (venueid, interestid) values (16, 32);
insert into venueinterestlink (venueid, interestid) values (16, 0);
insert into venueinterestlink (venueid, interestid) values (16, 44);
insert into venueinterestlink (venueid, interestid) values (16, 33);
insert into venueinterestlink (venueid, interestid) values (16, 61);
insert into venueinterestlink (venueid, interestid) values (16, 65);
insert into venueinterestlink (venueid, interestid) values (16, 55);
insert into venueinterestlink (venueid, interestid) values (16, 19);
insert into venueinterestlink (venueid, interestid) values (17, 13);
insert into venueinterestlink (venueid, interestid) values (17, 52);
insert into venueinterestlink (venueid, interestid) values (17, 57);
insert into venueinterestlink (venueid, interestid) values (17, 10);
insert into venueinterestlink (venueid, interestid) values (17, 7);
insert into venueinterestlink (venueid, interestid) values (17, 29);
insert into venueinterestlink (venueid, interestid) values (17, 23);
insert into venueinterestlink (venueid, interestid) values (17, 43);
insert into venueinterestlink (venueid, interestid) values (17, 59);
insert into venueinterestlink (venueid, interestid) values (17, 30);
insert into venueinterestlink (venueid, interestid) values (17, 12);
insert into venueinterestlink (venueid, interestid) values (17, 1);
insert into venueinterestlink (venueid, interestid) values (17, 21);
insert into venueinterestlink (venueid, interestid) values (17, 5);
insert into venueinterestlink (venueid, interestid) values (17, 63);
insert into venueinterestlink (venueid, interestid) values (17, 18);
insert into venueinterestlink (venueid, interestid) values (17, 46);
insert into venueinterestlink (venueid, interestid) values (17, 36);
insert into venueinterestlink (venueid, interestid) values (17, 8);
insert into venueinterestlink (venueid, interestid) values (17, 37);
insert into venueinterestlink (venueid, interestid) values (18, 15);
insert into venueinterestlink (venueid, interestid) values (18, 2);
insert into venueinterestlink (venueid, interestid) values (18, 10);
insert into venueinterestlink (venueid, interestid) values (18, 56);
insert into venueinterestlink (venueid, interestid) values (18, 60);
insert into venueinterestlink (venueid, interestid) values (18, 57);
insert into venueinterestlink (venueid, interestid) values (18, 41);
insert into venueinterestlink (venueid, interestid) values (18, 42);
insert into venueinterestlink (venueid, interestid) values (18, 18);
insert into venueinterestlink (venueid, interestid) values (18, 59);
insert into venueinterestlink (venueid, interestid) values (18, 30);
insert into venueinterestlink (venueid, interestid) values (18, 46);
insert into venueinterestlink (venueid, interestid) values (18, 44);
insert into venueinterestlink (venueid, interestid) values (18, 29);
insert into venueinterestlink (venueid, interestid) values (18, 63);
insert into venueinterestlink (venueid, interestid) values (18, 20);
insert into venueinterestlink (venueid, interestid) values (18, 7);
insert into venueinterestlink (venueid, interestid) values (18, 50);
insert into venueinterestlink (venueid, interestid) values (18, 22);
insert into venueinterestlink (venueid, interestid) values (18, 53);
insert into venueinterestlink (venueid, interestid) values (19, 42);
insert into venueinterestlink (venueid, interestid) values (19, 2);
insert into venueinterestlink (venueid, interestid) values (19, 39);
insert into venueinterestlink (venueid, interestid) values (19, 62);
insert into venueinterestlink (venueid, interestid) values (19, 22);
insert into venueinterestlink (venueid, interestid) values (19, 0);
insert into venueinterestlink (venueid, interestid) values (19, 1);
insert into venueinterestlink (venueid, interestid) values (19, 26);
insert into venueinterestlink (venueid, interestid) values (19, 20);
insert into venueinterestlink (venueid, interestid) values (19, 17);
insert into venueinterestlink (venueid, interestid) values (19, 48);
insert into venueinterestlink (venueid, interestid) values (19, 9);
insert into venueinterestlink (venueid, interestid) values (19, 33);
insert into venueinterestlink (venueid, interestid) values (19, 47);
insert into venueinterestlink (venueid, interestid) values (19, 57);
insert into venueinterestlink (venueid, interestid) values (19, 16);
insert into venueinterestlink (venueid, interestid) values (19, 46);
insert into venueinterestlink (venueid, interestid) values (19, 6);
insert into venueinterestlink (venueid, interestid) values (19, 21);
insert into venueinterestlink (venueid, interestid) values (19, 12);
insert into venueinterestlink (venueid, interestid) values (20, 59);
insert into venueinterestlink (venueid, interestid) values (20, 5);
insert into venueinterestlink (venueid, interestid) values (20, 61);
insert into venueinterestlink (venueid, interestid) values (20, 9);
insert into venueinterestlink (venueid, interestid) values (20, 35);
insert into venueinterestlink (venueid, interestid) values (20, 13);
insert into venueinterestlink (venueid, interestid) values (20, 6);
insert into venueinterestlink (venueid, interestid) values (20, 38);
insert into venueinterestlink (venueid, interestid) values (20, 56);
insert into venueinterestlink (venueid, interestid) values (20, 42);
insert into venueinterestlink (venueid, interestid) values (20, 43);
insert into venueinterestlink (venueid, interestid) values (20, 30);
insert into venueinterestlink (venueid, interestid) values (20, 39);
insert into venueinterestlink (venueid, interestid) values (20, 37);
insert into venueinterestlink (venueid, interestid) values (20, 51);
insert into venueinterestlink (venueid, interestid) values (20, 44);
insert into venueinterestlink (venueid, interestid) values (20, 53);
insert into venueinterestlink (venueid, interestid) values (20, 28);
insert into venueinterestlink (venueid, interestid) values (20, 26);
insert into venueinterestlink (venueid, interestid) values (20, 58);
insert into venueinterestlink (venueid, interestid) values (21, 36);
insert into venueinterestlink (venueid, interestid) values (21, 14);
insert into venueinterestlink (venueid, interestid) values (21, 64);
insert into venueinterestlink (venueid, interestid) values (21, 19);
insert into venueinterestlink (venueid, interestid) values (21, 43);
insert into venueinterestlink (venueid, interestid) values (21, 62);
insert into venueinterestlink (venueid, interestid) values (21, 57);
insert into venueinterestlink (venueid, interestid) values (21, 5);
insert into venueinterestlink (venueid, interestid) values (21, 50);
insert into venueinterestlink (venueid, interestid) values (21, 20);
insert into venueinterestlink (venueid, interestid) values (21, 46);
insert into venueinterestlink (venueid, interestid) values (21, 38);
insert into venueinterestlink (venueid, interestid) values (21, 34);
insert into venueinterestlink (venueid, interestid) values (21, 56);
insert into venueinterestlink (venueid, interestid) values (21, 44);
insert into venueinterestlink (venueid, interestid) values (21, 39);
insert into venueinterestlink (venueid, interestid) values (21, 55);
insert into venueinterestlink (venueid, interestid) values (21, 45);
insert into venueinterestlink (venueid, interestid) values (21, 58);
insert into venueinterestlink (venueid, interestid) values (21, 47);
insert into venueinterestlink (venueid, interestid) values (22, 9);
insert into venueinterestlink (venueid, interestid) values (22, 33);
insert into venueinterestlink (venueid, interestid) values (22, 60);
insert into venueinterestlink (venueid, interestid) values (22, 7);
insert into venueinterestlink (venueid, interestid) values (22, 38);
insert into venueinterestlink (venueid, interestid) values (22, 28);
insert into venueinterestlink (venueid, interestid) values (22, 5);
insert into venueinterestlink (venueid, interestid) values (22, 14);
insert into venueinterestlink (venueid, interestid) values (22, 59);
insert into venueinterestlink (venueid, interestid) values (22, 11);
insert into venueinterestlink (venueid, interestid) values (22, 39);
insert into venueinterestlink (venueid, interestid) values (22, 37);
insert into venueinterestlink (venueid, interestid) values (22, 50);
insert into venueinterestlink (venueid, interestid) values (22, 57);
insert into venueinterestlink (venueid, interestid) values (22, 65);
insert into venueinterestlink (venueid, interestid) values (22, 13);
insert into venueinterestlink (venueid, interestid) values (22, 30);
insert into venueinterestlink (venueid, interestid) values (22, 58);
insert into venueinterestlink (venueid, interestid) values (22, 41);
insert into venueinterestlink (venueid, interestid) values (22, 19);
insert into venueinterestlink (venueid, interestid) values (23, 12);
insert into venueinterestlink (venueid, interestid) values (23, 21);
insert into venueinterestlink (venueid, interestid) values (23, 38);
insert into venueinterestlink (venueid, interestid) values (23, 7);
insert into venueinterestlink (venueid, interestid) values (23, 35);
insert into venueinterestlink (venueid, interestid) values (23, 45);
insert into venueinterestlink (venueid, interestid) values (23, 54);
insert into venueinterestlink (venueid, interestid) values (23, 30);
insert into venueinterestlink (venueid, interestid) values (23, 22);
insert into venueinterestlink (venueid, interestid) values (23, 50);
insert into venueinterestlink (venueid, interestid) values (23, 51);
insert into venueinterestlink (venueid, interestid) values (23, 0);
insert into venueinterestlink (venueid, interestid) values (23, 14);
insert into venueinterestlink (venueid, interestid) values (23, 31);
insert into venueinterestlink (venueid, interestid) values (23, 37);
insert into venueinterestlink (venueid, interestid) values (23, 20);
insert into venueinterestlink (venueid, interestid) values (23, 41);
insert into venueinterestlink (venueid, interestid) values (23, 27);
insert into venueinterestlink (venueid, interestid) values (23, 44);
insert into venueinterestlink (venueid, interestid) values (23, 43);
insert into venueinterestlink (venueid, interestid) values (24, 34);
insert into venueinterestlink (venueid, interestid) values (24, 24);
insert into venueinterestlink (venueid, interestid) values (24, 56);
insert into venueinterestlink (venueid, interestid) values (24, 41);
insert into venueinterestlink (venueid, interestid) values (24, 0);
insert into venueinterestlink (venueid, interestid) values (24, 44);
insert into venueinterestlink (venueid, interestid) values (24, 2);
insert into venueinterestlink (venueid, interestid) values (24, 38);
insert into venueinterestlink (venueid, interestid) values (24, 11);
insert into venueinterestlink (venueid, interestid) values (24, 32);
insert into venueinterestlink (venueid, interestid) values (24, 1);
insert into venueinterestlink (venueid, interestid) values (24, 53);
insert into venueinterestlink (venueid, interestid) values (24, 31);
insert into venueinterestlink (venueid, interestid) values (24, 8);
insert into venueinterestlink (venueid, interestid) values (24, 63);
insert into venueinterestlink (venueid, interestid) values (24, 26);
insert into venueinterestlink (venueid, interestid) values (24, 30);
insert into venueinterestlink (venueid, interestid) values (24, 18);
insert into venueinterestlink (venueid, interestid) values (24, 16);
insert into venueinterestlink (venueid, interestid) values (24, 47);
insert into venueinterestlink (venueid, interestid) values (25, 53);
insert into venueinterestlink (venueid, interestid) values (25, 8);
insert into venueinterestlink (venueid, interestid) values (25, 58);
insert into venueinterestlink (venueid, interestid) values (25, 65);
insert into venueinterestlink (venueid, interestid) values (25, 55);
insert into venueinterestlink (venueid, interestid) values (25, 62);
insert into venueinterestlink (venueid, interestid) values (25, 15);
insert into venueinterestlink (venueid, interestid) values (25, 46);
insert into venueinterestlink (venueid, interestid) values (25, 33);
insert into venueinterestlink (venueid, interestid) values (25, 60);
insert into venueinterestlink (venueid, interestid) values (25, 5);
insert into venueinterestlink (venueid, interestid) values (25, 6);
insert into venueinterestlink (venueid, interestid) values (25, 20);
insert into venueinterestlink (venueid, interestid) values (25, 54);
insert into venueinterestlink (venueid, interestid) values (25, 24);
insert into venueinterestlink (venueid, interestid) values (25, 35);
insert into venueinterestlink (venueid, interestid) values (25, 11);
insert into venueinterestlink (venueid, interestid) values (25, 61);
insert into venueinterestlink (venueid, interestid) values (25, 2);
insert into venueinterestlink (venueid, interestid) values (25, 19);
insert into venueinterestlink (venueid, interestid) values (26, 54);
insert into venueinterestlink (venueid, interestid) values (26, 40);
insert into venueinterestlink (venueid, interestid) values (26, 5);
insert into venueinterestlink (venueid, interestid) values (26, 8);
insert into venueinterestlink (venueid, interestid) values (26, 13);
insert into venueinterestlink (venueid, interestid) values (26, 59);
insert into venueinterestlink (venueid, interestid) values (26, 24);
insert into venueinterestlink (venueid, interestid) values (26, 4);
insert into venueinterestlink (venueid, interestid) values (26, 61);
insert into venueinterestlink (venueid, interestid) values (26, 50);
insert into venueinterestlink (venueid, interestid) values (26, 25);
insert into venueinterestlink (venueid, interestid) values (26, 18);
insert into venueinterestlink (venueid, interestid) values (26, 34);
insert into venueinterestlink (venueid, interestid) values (26, 17);
insert into venueinterestlink (venueid, interestid) values (26, 28);
insert into venueinterestlink (venueid, interestid) values (26, 45);
insert into venueinterestlink (venueid, interestid) values (26, 60);
insert into venueinterestlink (venueid, interestid) values (26, 23);
insert into venueinterestlink (venueid, interestid) values (26, 44);
insert into venueinterestlink (venueid, interestid) values (26, 14);
insert into venueinterestlink (venueid, interestid) values (27, 29);
insert into venueinterestlink (venueid, interestid) values (27, 17);
insert into venueinterestlink (venueid, interestid) values (27, 18);
insert into venueinterestlink (venueid, interestid) values (27, 3);
insert into venueinterestlink (venueid, interestid) values (27, 49);
insert into venueinterestlink (venueid, interestid) values (27, 24);
insert into venueinterestlink (venueid, interestid) values (27, 13);
insert into venueinterestlink (venueid, interestid) values (27, 27);
insert into venueinterestlink (venueid, interestid) values (27, 53);
insert into venueinterestlink (venueid, interestid) values (27, 56);
insert into venueinterestlink (venueid, interestid) values (27, 6);
insert into venueinterestlink (venueid, interestid) values (27, 8);
insert into venueinterestlink (venueid, interestid) values (27, 59);
insert into venueinterestlink (venueid, interestid) values (27, 31);
insert into venueinterestlink (venueid, interestid) values (27, 25);
insert into venueinterestlink (venueid, interestid) values (27, 47);
insert into venueinterestlink (venueid, interestid) values (27, 16);
insert into venueinterestlink (venueid, interestid) values (27, 7);
insert into venueinterestlink (venueid, interestid) values (27, 19);
insert into venueinterestlink (venueid, interestid) values (27, 35);
insert into venueinterestlink (venueid, interestid) values (28, 16);
insert into venueinterestlink (venueid, interestid) values (28, 59);
insert into venueinterestlink (venueid, interestid) values (28, 47);
insert into venueinterestlink (venueid, interestid) values (28, 17);
insert into venueinterestlink (venueid, interestid) values (28, 54);
insert into venueinterestlink (venueid, interestid) values (28, 35);
insert into venueinterestlink (venueid, interestid) values (28, 13);
insert into venueinterestlink (venueid, interestid) values (28, 65);
insert into venueinterestlink (venueid, interestid) values (28, 45);
insert into venueinterestlink (venueid, interestid) values (28, 10);
insert into venueinterestlink (venueid, interestid) values (28, 50);
insert into venueinterestlink (venueid, interestid) values (28, 18);
insert into venueinterestlink (venueid, interestid) values (28, 8);
insert into venueinterestlink (venueid, interestid) values (28, 1);
insert into venueinterestlink (venueid, interestid) values (28, 38);
insert into venueinterestlink (venueid, interestid) values (28, 3);
insert into venueinterestlink (venueid, interestid) values (28, 9);
insert into venueinterestlink (venueid, interestid) values (28, 6);
insert into venueinterestlink (venueid, interestid) values (28, 5);
insert into venueinterestlink (venueid, interestid) values (28, 26);
insert into venueinterestlink (venueid, interestid) values (29, 3);
insert into venueinterestlink (venueid, interestid) values (29, 4);
insert into venueinterestlink (venueid, interestid) values (29, 34);
insert into venueinterestlink (venueid, interestid) values (29, 7);
insert into venueinterestlink (venueid, interestid) values (29, 28);
insert into venueinterestlink (venueid, interestid) values (29, 38);
insert into venueinterestlink (venueid, interestid) values (29, 11);
insert into venueinterestlink (venueid, interestid) values (29, 55);
insert into venueinterestlink (venueid, interestid) values (29, 44);
insert into venueinterestlink (venueid, interestid) values (29, 45);
insert into venueinterestlink (venueid, interestid) values (29, 61);
insert into venueinterestlink (venueid, interestid) values (29, 50);
insert into venueinterestlink (venueid, interestid) values (29, 31);
insert into venueinterestlink (venueid, interestid) values (29, 36);
insert into venueinterestlink (venueid, interestid) values (29, 57);
insert into venueinterestlink (venueid, interestid) values (29, 25);
insert into venueinterestlink (venueid, interestid) values (29, 8);
insert into venueinterestlink (venueid, interestid) values (29, 40);
insert into venueinterestlink (venueid, interestid) values (29, 35);
insert into venueinterestlink (venueid, interestid) values (29, 15);
insert into venueinterestlink (venueid, interestid) values (30, 18);
insert into venueinterestlink (venueid, interestid) values (30, 54);
insert into venueinterestlink (venueid, interestid) values (30, 29);
insert into venueinterestlink (venueid, interestid) values (30, 15);
insert into venueinterestlink (venueid, interestid) values (30, 62);
insert into venueinterestlink (venueid, interestid) values (30, 26);
insert into venueinterestlink (venueid, interestid) values (30, 19);
insert into venueinterestlink (venueid, interestid) values (30, 13);
insert into venueinterestlink (venueid, interestid) values (30, 25);
insert into venueinterestlink (venueid, interestid) values (30, 45);
insert into venueinterestlink (venueid, interestid) values (30, 3);
insert into venueinterestlink (venueid, interestid) values (30, 35);
insert into venueinterestlink (venueid, interestid) values (30, 47);
insert into venueinterestlink (venueid, interestid) values (30, 64);
insert into venueinterestlink (venueid, interestid) values (30, 8);
insert into venueinterestlink (venueid, interestid) values (30, 59);
insert into venueinterestlink (venueid, interestid) values (30, 49);
insert into venueinterestlink (venueid, interestid) values (30, 28);
insert into venueinterestlink (venueid, interestid) values (30, 11);
insert into venueinterestlink (venueid, interestid) values (30, 5);
insert into venueinterestlink (venueid, interestid) values (31, 60);
insert into venueinterestlink (venueid, interestid) values (31, 22);
insert into venueinterestlink (venueid, interestid) values (31, 42);
insert into venueinterestlink (venueid, interestid) values (31, 58);
insert into venueinterestlink (venueid, interestid) values (31, 5);
insert into venueinterestlink (venueid, interestid) values (31, 36);
insert into venueinterestlink (venueid, interestid) values (31, 51);
insert into venueinterestlink (venueid, interestid) values (31, 3);
insert into venueinterestlink (venueid, interestid) values (31, 30);
insert into venueinterestlink (venueid, interestid) values (31, 41);
insert into venueinterestlink (venueid, interestid) values (31, 64);
insert into venueinterestlink (venueid, interestid) values (31, 33);
insert into venueinterestlink (venueid, interestid) values (31, 63);
insert into venueinterestlink (venueid, interestid) values (31, 55);
insert into venueinterestlink (venueid, interestid) values (31, 17);
insert into venueinterestlink (venueid, interestid) values (31, 12);
insert into venueinterestlink (venueid, interestid) values (31, 18);
insert into venueinterestlink (venueid, interestid) values (31, 61);
insert into venueinterestlink (venueid, interestid) values (31, 25);
insert into venueinterestlink (venueid, interestid) values (31, 45);
insert into venueinterestlink (venueid, interestid) values (32, 53);
insert into venueinterestlink (venueid, interestid) values (32, 65);
insert into venueinterestlink (venueid, interestid) values (32, 17);
insert into venueinterestlink (venueid, interestid) values (32, 11);
insert into venueinterestlink (venueid, interestid) values (32, 36);
insert into venueinterestlink (venueid, interestid) values (32, 12);
insert into venueinterestlink (venueid, interestid) values (32, 57);
insert into venueinterestlink (venueid, interestid) values (32, 8);
insert into venueinterestlink (venueid, interestid) values (32, 26);
insert into venueinterestlink (venueid, interestid) values (32, 60);
insert into venueinterestlink (venueid, interestid) values (32, 55);
insert into venueinterestlink (venueid, interestid) values (32, 13);
insert into venueinterestlink (venueid, interestid) values (32, 20);
insert into venueinterestlink (venueid, interestid) values (32, 59);
insert into venueinterestlink (venueid, interestid) values (32, 10);
insert into venueinterestlink (venueid, interestid) values (32, 58);
insert into venueinterestlink (venueid, interestid) values (32, 0);
insert into venueinterestlink (venueid, interestid) values (32, 49);
insert into venueinterestlink (venueid, interestid) values (32, 33);
insert into venueinterestlink (venueid, interestid) values (32, 39);
insert into venueinterestlink (venueid, interestid) values (33, 15);
insert into venueinterestlink (venueid, interestid) values (33, 63);
insert into venueinterestlink (venueid, interestid) values (33, 1);
insert into venueinterestlink (venueid, interestid) values (33, 47);
insert into venueinterestlink (venueid, interestid) values (33, 52);
insert into venueinterestlink (venueid, interestid) values (33, 35);
insert into venueinterestlink (venueid, interestid) values (33, 5);
insert into venueinterestlink (venueid, interestid) values (33, 48);
insert into venueinterestlink (venueid, interestid) values (33, 32);
insert into venueinterestlink (venueid, interestid) values (33, 19);
insert into venueinterestlink (venueid, interestid) values (33, 40);
insert into venueinterestlink (venueid, interestid) values (33, 26);
insert into venueinterestlink (venueid, interestid) values (33, 10);
insert into venueinterestlink (venueid, interestid) values (33, 56);
insert into venueinterestlink (venueid, interestid) values (33, 54);
insert into venueinterestlink (venueid, interestid) values (33, 57);
insert into venueinterestlink (venueid, interestid) values (33, 18);
insert into venueinterestlink (venueid, interestid) values (33, 21);
insert into venueinterestlink (venueid, interestid) values (33, 62);
insert into venueinterestlink (venueid, interestid) values (33, 29);
insert into venueinterestlink (venueid, interestid) values (34, 27);
insert into venueinterestlink (venueid, interestid) values (34, 42);
insert into venueinterestlink (venueid, interestid) values (34, 50);
insert into venueinterestlink (venueid, interestid) values (34, 51);
insert into venueinterestlink (venueid, interestid) values (34, 19);
insert into venueinterestlink (venueid, interestid) values (34, 43);
insert into venueinterestlink (venueid, interestid) values (34, 36);
insert into venueinterestlink (venueid, interestid) values (34, 23);
insert into venueinterestlink (venueid, interestid) values (34, 45);
insert into venueinterestlink (venueid, interestid) values (34, 35);
insert into venueinterestlink (venueid, interestid) values (34, 44);
insert into venueinterestlink (venueid, interestid) values (34, 40);
insert into venueinterestlink (venueid, interestid) values (34, 38);
insert into venueinterestlink (venueid, interestid) values (34, 25);
insert into venueinterestlink (venueid, interestid) values (34, 4);
insert into venueinterestlink (venueid, interestid) values (34, 22);
insert into venueinterestlink (venueid, interestid) values (34, 24);
insert into venueinterestlink (venueid, interestid) values (34, 54);
insert into venueinterestlink (venueid, interestid) values (34, 8);
insert into venueinterestlink (venueid, interestid) values (34, 15);
insert into venueinterestlink (venueid, interestid) values (35, 23);
insert into venueinterestlink (venueid, interestid) values (35, 1);
insert into venueinterestlink (venueid, interestid) values (35, 33);
insert into venueinterestlink (venueid, interestid) values (35, 39);
insert into venueinterestlink (venueid, interestid) values (35, 56);
insert into venueinterestlink (venueid, interestid) values (35, 48);
insert into venueinterestlink (venueid, interestid) values (35, 11);
insert into venueinterestlink (venueid, interestid) values (35, 8);
insert into venueinterestlink (venueid, interestid) values (35, 37);
insert into venueinterestlink (venueid, interestid) values (35, 12);
insert into venueinterestlink (venueid, interestid) values (35, 36);
insert into venueinterestlink (venueid, interestid) values (35, 44);
insert into venueinterestlink (venueid, interestid) values (35, 52);
insert into venueinterestlink (venueid, interestid) values (35, 10);
insert into venueinterestlink (venueid, interestid) values (35, 51);
insert into venueinterestlink (venueid, interestid) values (35, 19);
insert into venueinterestlink (venueid, interestid) values (35, 41);
insert into venueinterestlink (venueid, interestid) values (35, 50);
insert into venueinterestlink (venueid, interestid) values (35, 28);
insert into venueinterestlink (venueid, interestid) values (35, 3);
insert into venueinterestlink (venueid, interestid) values (36, 31);
insert into venueinterestlink (venueid, interestid) values (36, 52);
insert into venueinterestlink (venueid, interestid) values (36, 51);
insert into venueinterestlink (venueid, interestid) values (36, 2);
insert into venueinterestlink (venueid, interestid) values (36, 3);
insert into venueinterestlink (venueid, interestid) values (36, 18);
insert into venueinterestlink (venueid, interestid) values (36, 49);
insert into venueinterestlink (venueid, interestid) values (36, 26);
insert into venueinterestlink (venueid, interestid) values (36, 10);
insert into venueinterestlink (venueid, interestid) values (36, 57);
insert into venueinterestlink (venueid, interestid) values (36, 55);
insert into venueinterestlink (venueid, interestid) values (36, 20);
insert into venueinterestlink (venueid, interestid) values (36, 15);
insert into venueinterestlink (venueid, interestid) values (36, 5);
insert into venueinterestlink (venueid, interestid) values (36, 53);
insert into venueinterestlink (venueid, interestid) values (36, 63);
insert into venueinterestlink (venueid, interestid) values (36, 28);
insert into venueinterestlink (venueid, interestid) values (36, 36);
insert into venueinterestlink (venueid, interestid) values (36, 22);
insert into venueinterestlink (venueid, interestid) values (36, 60);
insert into venueinterestlink (venueid, interestid) values (37, 44);
insert into venueinterestlink (venueid, interestid) values (37, 24);
insert into venueinterestlink (venueid, interestid) values (37, 65);
insert into venueinterestlink (venueid, interestid) values (37, 39);
insert into venueinterestlink (venueid, interestid) values (37, 61);
insert into venueinterestlink (venueid, interestid) values (37, 26);
insert into venueinterestlink (venueid, interestid) values (37, 5);
insert into venueinterestlink (venueid, interestid) values (37, 48);
insert into venueinterestlink (venueid, interestid) values (37, 14);
insert into venueinterestlink (venueid, interestid) values (37, 45);
insert into venueinterestlink (venueid, interestid) values (37, 58);
insert into venueinterestlink (venueid, interestid) values (37, 52);
insert into venueinterestlink (venueid, interestid) values (37, 50);
insert into venueinterestlink (venueid, interestid) values (37, 25);
insert into venueinterestlink (venueid, interestid) values (37, 62);
insert into venueinterestlink (venueid, interestid) values (37, 22);
insert into venueinterestlink (venueid, interestid) values (37, 38);
insert into venueinterestlink (venueid, interestid) values (37, 20);
insert into venueinterestlink (venueid, interestid) values (37, 15);
insert into venueinterestlink (venueid, interestid) values (37, 12);
insert into venueinterestlink (venueid, interestid) values (38, 30);
insert into venueinterestlink (venueid, interestid) values (38, 51);
insert into venueinterestlink (venueid, interestid) values (38, 38);
insert into venueinterestlink (venueid, interestid) values (38, 23);
insert into venueinterestlink (venueid, interestid) values (38, 11);
insert into venueinterestlink (venueid, interestid) values (38, 8);
insert into venueinterestlink (venueid, interestid) values (38, 41);
insert into venueinterestlink (venueid, interestid) values (38, 31);
insert into venueinterestlink (venueid, interestid) values (38, 64);
insert into venueinterestlink (venueid, interestid) values (38, 44);
insert into venueinterestlink (venueid, interestid) values (38, 42);
insert into venueinterestlink (venueid, interestid) values (38, 19);
insert into venueinterestlink (venueid, interestid) values (38, 32);
insert into venueinterestlink (venueid, interestid) values (38, 12);
insert into venueinterestlink (venueid, interestid) values (38, 55);
insert into venueinterestlink (venueid, interestid) values (38, 39);
insert into venueinterestlink (venueid, interestid) values (38, 40);
insert into venueinterestlink (venueid, interestid) values (38, 59);
insert into venueinterestlink (venueid, interestid) values (38, 1);
insert into venueinterestlink (venueid, interestid) values (38, 34);
insert into venueinterestlink (venueid, interestid) values (39, 62);
insert into venueinterestlink (venueid, interestid) values (39, 47);
insert into venueinterestlink (venueid, interestid) values (39, 49);
insert into venueinterestlink (venueid, interestid) values (39, 19);
insert into venueinterestlink (venueid, interestid) values (39, 15);
insert into venueinterestlink (venueid, interestid) values (39, 63);
insert into venueinterestlink (venueid, interestid) values (39, 34);
insert into venueinterestlink (venueid, interestid) values (39, 59);
insert into venueinterestlink (venueid, interestid) values (39, 1);
insert into venueinterestlink (venueid, interestid) values (39, 9);
insert into venueinterestlink (venueid, interestid) values (39, 39);
insert into venueinterestlink (venueid, interestid) values (39, 45);
insert into venueinterestlink (venueid, interestid) values (39, 6);
insert into venueinterestlink (venueid, interestid) values (39, 46);
insert into venueinterestlink (venueid, interestid) values (39, 64);
insert into venueinterestlink (venueid, interestid) values (39, 61);
insert into venueinterestlink (venueid, interestid) values (39, 11);
insert into venueinterestlink (venueid, interestid) values (39, 14);
insert into venueinterestlink (venueid, interestid) values (39, 55);
insert into venueinterestlink (venueid, interestid) values (39, 57);
insert into venueinterestlink (venueid, interestid) values (40, 24);
insert into venueinterestlink (venueid, interestid) values (40, 4);
insert into venueinterestlink (venueid, interestid) values (40, 13);
insert into venueinterestlink (venueid, interestid) values (40, 0);
insert into venueinterestlink (venueid, interestid) values (40, 10);
insert into venueinterestlink (venueid, interestid) values (40, 28);
insert into venueinterestlink (venueid, interestid) values (40, 62);
insert into venueinterestlink (venueid, interestid) values (40, 52);
insert into venueinterestlink (venueid, interestid) values (40, 31);
insert into venueinterestlink (venueid, interestid) values (40, 9);
insert into venueinterestlink (venueid, interestid) values (40, 64);
insert into venueinterestlink (venueid, interestid) values (40, 37);
insert into venueinterestlink (venueid, interestid) values (40, 23);
insert into venueinterestlink (venueid, interestid) values (40, 7);
insert into venueinterestlink (venueid, interestid) values (40, 51);
insert into venueinterestlink (venueid, interestid) values (40, 3);
insert into venueinterestlink (venueid, interestid) values (40, 14);
insert into venueinterestlink (venueid, interestid) values (40, 1);
insert into venueinterestlink (venueid, interestid) values (40, 26);
insert into venueinterestlink (venueid, interestid) values (40, 15);
insert into venueinterestlink (venueid, interestid) values (41, 21);
insert into venueinterestlink (venueid, interestid) values (41, 42);
insert into venueinterestlink (venueid, interestid) values (41, 6);
insert into venueinterestlink (venueid, interestid) values (41, 50);
insert into venueinterestlink (venueid, interestid) values (41, 14);
insert into venueinterestlink (venueid, interestid) values (41, 16);
insert into venueinterestlink (venueid, interestid) values (41, 39);
insert into venueinterestlink (venueid, interestid) values (41, 62);
insert into venueinterestlink (venueid, interestid) values (41, 0);
insert into venueinterestlink (venueid, interestid) values (41, 8);
insert into venueinterestlink (venueid, interestid) values (41, 37);
insert into venueinterestlink (venueid, interestid) values (41, 24);
insert into venueinterestlink (venueid, interestid) values (41, 9);
insert into venueinterestlink (venueid, interestid) values (41, 49);
insert into venueinterestlink (venueid, interestid) values (41, 41);
insert into venueinterestlink (venueid, interestid) values (41, 7);
insert into venueinterestlink (venueid, interestid) values (41, 34);
insert into venueinterestlink (venueid, interestid) values (41, 2);
insert into venueinterestlink (venueid, interestid) values (41, 1);
insert into venueinterestlink (venueid, interestid) values (41, 28);
insert into venueinterestlink (venueid, interestid) values (42, 22);
insert into venueinterestlink (venueid, interestid) values (42, 40);
insert into venueinterestlink (venueid, interestid) values (42, 55);
insert into venueinterestlink (venueid, interestid) values (42, 45);
insert into venueinterestlink (venueid, interestid) values (42, 30);
insert into venueinterestlink (venueid, interestid) values (42, 8);
insert into venueinterestlink (venueid, interestid) values (42, 24);
insert into venueinterestlink (venueid, interestid) values (42, 65);
insert into venueinterestlink (venueid, interestid) values (42, 56);
insert into venueinterestlink (venueid, interestid) values (42, 53);
insert into venueinterestlink (venueid, interestid) values (42, 63);
insert into venueinterestlink (venueid, interestid) values (42, 20);
insert into venueinterestlink (venueid, interestid) values (42, 47);
insert into venueinterestlink (venueid, interestid) values (42, 16);
insert into venueinterestlink (venueid, interestid) values (42, 26);
insert into venueinterestlink (venueid, interestid) values (42, 41);
insert into venueinterestlink (venueid, interestid) values (42, 38);
insert into venueinterestlink (venueid, interestid) values (42, 27);
insert into venueinterestlink (venueid, interestid) values (42, 58);
insert into venueinterestlink (venueid, interestid) values (42, 7);
insert into venueinterestlink (venueid, interestid) values (43, 32);
insert into venueinterestlink (venueid, interestid) values (43, 54);
insert into venueinterestlink (venueid, interestid) values (43, 1);
insert into venueinterestlink (venueid, interestid) values (43, 57);
insert into venueinterestlink (venueid, interestid) values (43, 15);
insert into venueinterestlink (venueid, interestid) values (43, 14);
insert into venueinterestlink (venueid, interestid) values (43, 41);
insert into venueinterestlink (venueid, interestid) values (43, 23);
insert into venueinterestlink (venueid, interestid) values (43, 59);
insert into venueinterestlink (venueid, interestid) values (43, 27);
insert into venueinterestlink (venueid, interestid) values (43, 65);
insert into venueinterestlink (venueid, interestid) values (43, 56);
insert into venueinterestlink (venueid, interestid) values (43, 24);
insert into venueinterestlink (venueid, interestid) values (43, 36);
insert into venueinterestlink (venueid, interestid) values (43, 33);
insert into venueinterestlink (venueid, interestid) values (43, 13);
insert into venueinterestlink (venueid, interestid) values (43, 42);
insert into venueinterestlink (venueid, interestid) values (43, 53);
insert into venueinterestlink (venueid, interestid) values (43, 18);
insert into venueinterestlink (venueid, interestid) values (43, 26);
insert into venueinterestlink (venueid, interestid) values (44, 16);
insert into venueinterestlink (venueid, interestid) values (44, 60);
insert into venueinterestlink (venueid, interestid) values (44, 10);
insert into venueinterestlink (venueid, interestid) values (44, 49);
insert into venueinterestlink (venueid, interestid) values (44, 63);
insert into venueinterestlink (venueid, interestid) values (44, 4);
insert into venueinterestlink (venueid, interestid) values (44, 2);
insert into venueinterestlink (venueid, interestid) values (44, 44);
insert into venueinterestlink (venueid, interestid) values (44, 3);
insert into venueinterestlink (venueid, interestid) values (44, 14);
insert into venueinterestlink (venueid, interestid) values (44, 41);
insert into venueinterestlink (venueid, interestid) values (44, 46);
insert into venueinterestlink (venueid, interestid) values (44, 26);
insert into venueinterestlink (venueid, interestid) values (44, 33);
insert into venueinterestlink (venueid, interestid) values (44, 42);
insert into venueinterestlink (venueid, interestid) values (44, 9);
insert into venueinterestlink (venueid, interestid) values (44, 21);
insert into venueinterestlink (venueid, interestid) values (44, 51);
insert into venueinterestlink (venueid, interestid) values (44, 40);
insert into venueinterestlink (venueid, interestid) values (44, 20);
insert into venueinterestlink (venueid, interestid) values (45, 59);
insert into venueinterestlink (venueid, interestid) values (45, 35);
insert into venueinterestlink (venueid, interestid) values (45, 16);
insert into venueinterestlink (venueid, interestid) values (45, 23);
insert into venueinterestlink (venueid, interestid) values (45, 33);
insert into venueinterestlink (venueid, interestid) values (45, 19);
insert into venueinterestlink (venueid, interestid) values (45, 58);
insert into venueinterestlink (venueid, interestid) values (45, 62);
insert into venueinterestlink (venueid, interestid) values (45, 9);
insert into venueinterestlink (venueid, interestid) values (45, 28);
insert into venueinterestlink (venueid, interestid) values (45, 60);
insert into venueinterestlink (venueid, interestid) values (45, 46);
insert into venueinterestlink (venueid, interestid) values (45, 56);
insert into venueinterestlink (venueid, interestid) values (45, 53);
insert into venueinterestlink (venueid, interestid) values (45, 13);
insert into venueinterestlink (venueid, interestid) values (45, 43);
insert into venueinterestlink (venueid, interestid) values (45, 22);
insert into venueinterestlink (venueid, interestid) values (45, 54);
insert into venueinterestlink (venueid, interestid) values (45, 61);
insert into venueinterestlink (venueid, interestid) values (45, 45);
insert into venueinterestlink (venueid, interestid) values (46, 59);
insert into venueinterestlink (venueid, interestid) values (46, 38);
insert into venueinterestlink (venueid, interestid) values (46, 46);
insert into venueinterestlink (venueid, interestid) values (46, 47);
insert into venueinterestlink (venueid, interestid) values (46, 53);
insert into venueinterestlink (venueid, interestid) values (46, 7);
insert into venueinterestlink (venueid, interestid) values (46, 21);
insert into venueinterestlink (venueid, interestid) values (46, 65);
insert into venueinterestlink (venueid, interestid) values (46, 8);
insert into venueinterestlink (venueid, interestid) values (46, 15);
insert into venueinterestlink (venueid, interestid) values (46, 62);
insert into venueinterestlink (venueid, interestid) values (46, 61);
insert into venueinterestlink (venueid, interestid) values (46, 50);
insert into venueinterestlink (venueid, interestid) values (46, 4);
insert into venueinterestlink (venueid, interestid) values (46, 39);
insert into venueinterestlink (venueid, interestid) values (46, 51);
insert into venueinterestlink (venueid, interestid) values (46, 40);
insert into venueinterestlink (venueid, interestid) values (46, 34);
insert into venueinterestlink (venueid, interestid) values (46, 6);
insert into venueinterestlink (venueid, interestid) values (46, 26);
